<?php
// $Id$

//  Module: arachis_recent_pubs

// Sudhansu Dash
// 2016 March 24


/**
 * Implements hook_menu().
 */

function arachis_recent_pubs_menu() {
  $items = array();
  $items['publications/arachis_recent_pubs'] = array( //this creates a URL
    'title' => 'Recent Peanut Publications', //page title
    'description' => 'List of recent peanut/Arachis publications from Pubmed via Eutils and JS http request.',
    'page callback' => arachis_recent_pubs_page_callback, //this function called when page accessed. For form, use drupal_get_form
    //'page arguments' => array('grin_acc_query_form'), //form name here // No need if page callback fn() doesn't need it.
    'access callback' => TRUE,
  );
  return $items;
}


/**
 * Implements hook_theme().
 */

function arachis_recent_pubs_theme() {
  return array(
    'arachis_recent_pubs_page_template' => array(  // this array name to be used in theme()
    'template' => 'arachis_recent_pubs_page',  //,  template file lis_citations_page.tpl.php
    //'variables' => array(),
    ),  //array page_template
  );  // array return
}    

/**
 * Implements page callback.
 */

function arachis_recent_pubs_page_callback() {
    $period = 3;
    return theme ('arachis_recent_pubs_page_template', array('period'=>$period)); 
}
